apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-ok-deployment
  labels:
    app: go-ok
    system: example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-ok
  template:
    metadata:
      labels:
        app: go-ok
        system: example
    spec:
      containers:
        - name: go-ok-container
          image: cjimti/go-ok:v3
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          ports:
            - name: go-ok-port
              containerPort: 8080