apiVersion: apps/v1
kind: Deployment
metadata:
  name: ok
  labels:
    app: ok
    system: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ok
  template:
    metadata:
      labels:
        app: ok
        system: example
    spec:
      containers:
        - name: ok
          image: txn2/ok
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          ports:
            - name: ok-port
              containerPort: 8080